### ISSUE TITLE
Request for Comment - Changing from GitBook

### ISSUE THREAD

**Issue by stroomdev07** [gchq/stroom-docs#55] opened 2021-03-18 12:31 UTC
There's been renewed discussion on drastically improving the overall look and feel of Stroom documentation. 

Any ideas for new tools that may be suitable, requirements or enhancements that a new tool may fulfil would be most helpful.

**Comment by at055612** [comment] 2021-03-18 13:44
closing as duplicate of #27

**Closed by at055612** 2021-03-18 13:44 UTC
